### PR TITLE
Re-queue messages from the losing chain segment in a re-org so that nonces are consistent with the pool.

### LINKED ISSUE #3052: [bug] Same actor and nonce but different cid
**Describe the bug**
This error has been seen in 0.2.4 and 0.3.0 version several times, when there are staged sectors waiting in line for sealing. 

`[0;37m16:29:28.595 [31mERROR [0;34m      node: [0mfailed to send commitSector message from t1kbn...yny to t2kab...xvi for sector with id 33....26: failed to add message to message pool: validation error adding message to pool: message pool contains message with same actor and nonce but different cid [0;37mnode.go:1110[0m`

And, I talked with some other miners, they got this too.

**To Reproduce**
Do not need to do any special steps, just send asks as fast as you can, and check the output log, then you will see this some time. 

**Expected behavior**
The nonce is increasing always, no same nonces for two messages in one miner's system.

**Version information**
Found in both test-devnet-0.2.2 and test-devnet-0.3.2

**Additional context**
Could there be race condition happened when multiple sectors for seal, especially when multiple workers are running?

### PR DESCRIPTION
**Pull request by anorth**
Fixes #3052 (see discussion there for discussion of alternatives).

### CODE REVIEW

**Comment by icorderi** [comment]
Is the solution of resubmitting the messages on the "alternative" head sound?
Since there is a new state, some of the messages might no longer be applicable, isn't safer to reject all messages that are not present on the new chain?

File: core/policy.go [hunk 1]
```diff
@@ -54,7 +55,22 @@ func NewMessageQueuePolicy(messages MessageProvider, maxAge uint) *DefaultQueueP
...
 func (p *DefaultQueuePolicy) HandleNewHead(ctx context.Context, target PolicyTarget, oldTips, newTips []types.TipSet) error {
-	// Rearrange the tipsets into increasing height order so messages are discovered in nonce order.
+	chainHeight := uint64(0)
+	var err error
+	if len(newTips) > 0 {
+		chainHeight, err = newTips[0].Height()
+		if err != nil {
+			return err
+		}
+	} else if len(oldTips) > 0 { // A pure rewind is unlikely in practice.
```
Comment (acruikshank) [inline core/policy.go]: This is a little weird. Seems like the only consequence of this clause is that the message requeued will be stamped with the maximum old chain height. It would be more accurate to use the minimum old chain height. Like you say, this is unlikely (impossible?) and the consequences seem small, so seems fine.

Comment (anorth) [reply core/policy.go]: I opted for the maximum as a "safe" option, to prevent premature expiration.

**Comment by anorth** [comment]
@icorderi the goal is to match the behaviour of the message pool (with which this may one day be merged). The pool definitely needs to make un-mined messages available for inclusion in new blocks else such messages would be lost entirely.

In practise, this works very well nearly all the time: the message nonce means messages must apply to a single actor's state in the order they were generated. If multiple messages with the same actor and nonce are generated (on different nodes) then it's possible for a subsequent message to have differing assumptions about the prior state, but this can't generally be avoided in such a distributed system, except by waiting for messages to apply or expire. It's generally considered much more useful to keep trying to apply messages (and have message semantics that make this ok) than to bump the problem back up to the user or system that wants to send a message. We borrow these ideas from prior art like Ethereum.
