### PR TITLE
Graphsync fetcher fixed recursive selector to include messages/receipts, verifies their fetch

### LINKED ISSUE #3220: [bug] Failure to sync tipset received from hello, could not load message collection
**Describe the bug**
On the 0.4.0 staging network, node are failing to sync the chain past height 55, because the message collection for a block at height 56 is not found in the store.

First reported in #3207, this issue is focussed on that specific problem.

It appears that there's a chain of ~3k blocks, but it doesn't validate.

```
13:44:29.027  INFO chain.sync: processing block 0 of 3040 for chain with head at { bafy2bzaceacrcn3ye7izsr7v26xwenzchjz5ocobtt3svpvmlm662b5p3ys7q bafy2bzaceazddktvonc3qijgiceri6tqnrzezi2n23yptucndojvugu3z52dc bafy2bzacecwnkysjfixkpuf5lvqyq3sho67vaksvu2l7yuzkow27633fbg4ay } syncer.go:396
```

Later...
```
13:44:29.580  INFO       node: error handling blocks: { bafy2bzaceacrcn3ye7izsr7v26xwenzchjz5ocobtt3svpvmlm662b5p3ys7q bafy2bzaceazddktvonc3qijgiceri6tqnrzezi2n23yptucndojvugu3z52dc bafy2bzacecwnkysjfixkpuf5lvqyq3sho67vaksvu2l7yuzkow27633fbg4ay } node.go:573
13:44:29.955  INFO       node: error handling blocks: { bafy2bzaceacrcn3ye7izsr7v26xwenzchjz5ocobtt3svpvmlm662b5p3ys7q bafy2bzaceazddktvonc3qijgiceri6tqnrzezi2n23yptucndojvugu3z52dc bafy2bzacecwnkysjfixkpuf5lvqyq3sho67vaksvu2l7yuzkow27633fbg4ay } node.go:573
13:44:30.428  INFO       node: error handling blocks: { bafy2bzaceacrcn3ye7izsr7v26xwenzchjz5ocobtt3svpvmlm662b5p3ys7q bafy2bzaceazddktvonc3qijgiceri6tqnrzezi2n23yptucndojvugu3z52dc bafy2bzacecwnkysjfixkpuf5lvqyq3sho67vaksvu2l7yuzkow27633fbg4ay } node.go:573
13:44:30.798  INFO       node: error handling blocks: { bafy2bzaceacrcn3ye7izsr7v26xwenzchjz5ocobtt3svpvmlm662b5p3ys7q bafy2bzaceazddktvonc3qijgiceri6tqnrzezi2n23yptucndojvugu3z52dc bafy2bzacecwnkysjfixkpuf5lvqyq3sho67vaksvu2l7yuzkow27633fbg4ay } node.go:573
13:44:31.167  INFO       node: error handling blocks: { bafy2bzaceacrcn3ye7izsr7v26xwenzchjz5ocobtt3svpvmlm662b5p3ys7q bafy2bzaceazddktvonc3qijgiceri6tqnrzezi2n23yptucndojvugu3z52dc bafy2bzacecwnkysjfixkpuf5lvqyq3sho67vaksvu2l7yuzkow27633fbg4ay } node.go:573
13:44:31.510  INFO       node: error handling blocks: { bafy2bzaceacrcn3ye7izsr7v26xwenzchjz5ocobtt3svpvmlm662b5p3ys7q bafy2bzaceazddktvonc3qijgiceri6tqnrzezi2n23yptucndojvugu3z52dc bafy2bzacecwnkysjfixkpuf5lvqyq3sho67vaksvu2l7yuzkow27633fbg4ay } node.go:573
13:44:31.931  INFO       node: error handling blocks: { bafy2bzaceacrcn3ye7izsr7v26xwenzchjz5ocobtt3svpvmlm662b5p3ys7q bafy2bzaceazddktvonc3qijgiceri6tqnrzezi2n23yptucndojvugu3z52dc bafy2bzacecwnkysjfixkpuf5lvqyq3sho67vaksvu2l7yuzkow27633fbg4ay } node.go:573
13:44:42.090  INFO       node: Received new block from network cid: bafy2bzacea2sscejbgyrnnosg7ngtgeuyqvoqqoy6lgkwxpjvxt6gstsdgzly block.go:57
13:44:43.036 ERROR       node: error in handler github.com/filecoin-project/go-filecoin/node.(*Node).processBlock-fm for topic /fil/blocks/devnet-3: processing block from network: could not load message collection with cid: bafy2bzacecapgrw3gypgdszigx6du3saedctf6ezzucjzbxl6xieo63zvzylw: blockservice: key not found node.go:1059
13:44:43.874  INFO       node: Received new block from network cid: bafy2bzacedzmu2aul5d2tuklonuybqz2tt5ulywudt66jeiaqp2md4y7sbkug block.go:57
13:44:46.126 ERROR       node: error in handler github.com/filecoin-project/go-filecoin/node.(*Node).processBlock-fm for topic /fil/blocks/devnet-3: processing block from network: could not load message collection with cid: bafy2bzacecapgrw3gypgdszigx6du3saedctf6ezzucjzbxl6xieo63zvzylw: blockservice: key not found node.go:1059
13:46:18.322  INFO       node: Received new block from network cid: bafy2bzaceav4wuw63ab7nyg5c5omabir2zmh6q7e6wrxtz4siqn742sd32wd2 block.go:57
13:46:18.922 ERROR       node: error in handler github.com/filecoin-project/go-filecoin/node.(*Node).processBlock-fm for topic /fil/blocks/devnet-3: processing block from network: could not load message collection with cid: bafy2bzacecapgrw3gypgdszigx6du3saedctf6ezzucjzbxl6xieo63zvzylw: blockservice: key not found node.go:1059
13:46:45.926  INFO       node: Received new block from network cid: bafy2bzacecbvmrhqcectv2mgdih3jkasepqaaqtxfy3zv4vh2o2wwsae3zkds block.go:57
13:46:46.499 ERROR       node: error in handler github.com/filecoin-project/go-filecoin/node.(*Node).processBlock-fm for topic /fil/blocks/devnet-3: processing block from network: could not load message collection with cid: bafy2bzacecapgrw3gypgdszigx6du3saedctf6ezzucjzbxl6xieo63zvzylw: blockservice: key not found node.go:1059
13:46:49.327  INFO       node: Received new block from network cid: bafy2bzacec33hf6kd3uwc3mtflayjouwciqiypjf6j7umjyz3agr7wwzq2dka block.go:57
13:46:49.898 ERROR       node: error in handler github.com/filecoin-project/go-filecoin/node.(*Node).processBlock-fm for topic /fil/blocks/devnet-3: processing block from network: could not load message collection with cid: bafy2bzacecapgrw3gypgdszigx6du3saedctf6ezzucjzbxl6xieo63zvzylw: blockservice: key not found node.go:1059
```
The [block explorer](https://explorer.staging.kittyhawk.wtf/) reports a height of ~5174 (~43 hrs) and is making progress, so the bootstrap node/s appear to be progressing, but others can't sync that chain.

According to my chain, the tip at height 55 has two blocks:
`{bafy2bzaceabftoi3xpfpfmkehpxn7fwdpc722wakorx42xzcs3cn2eubr3dzc, bafy2bzacecqsyt2tlsjgza4b77u4n4fc4ugplw2jgch3a6yrhb2mpij343ius
}`. This is the last one that validates locally.

By hacking in some better error messages, I can see the problem:
```
14:36:37.523  INFO       node: error handling tipset from hello {peer=QmXhxqTKzBKHA5FcMuiKZv8YaMPwpbKGXHRVZcFB2DX9XY height=5232 head={ bafy2bzacedimud2s74t3vdghaofdfhtnp6i7aacfoydg3djirewnfkst3tzyc }}: failed to sync { bafy2bzaceaxez2uzxtm6ffok76rtksr3lt3ta5hmu3ver6mlirk3knuibqrmq bafy2bzaceddo4xesg4rgojji3ecr55zamsucnupryasrthw5btst7wghwotoq }: failed loading messages for bafy2bzaceddo4xesg4rgojji3ecr55zamsucnupryasrthw5btst7wghwotoq: failed to load messages bafy2bzacecapgrw3gypgdszigx6du3saedctf6ezzucjzbxl6xieo63zvzylw: blockservice: key not found node.go:573
```

Tip height 56 is `{ bafy2bzaceaxez2uzxtm6ffok76rtksr3lt3ta5hmu3ver6mlirk3knuibqrmq bafy2bzaceddo4xesg4rgojji3ecr55zamsucnupryasrthw5btst7wghwotoq }` and [bafy2bzaceddo4xesg4rgojji3ecr55zamsucnupryasrthw5btst7wghwotoq](https://explorer.staging.kittyhawk.wtf/blocks/bafy2bzaceddo4xesg4rgojji3ecr55zamsucnupryasrthw5btst7wghwotoq) has a single message. It is *not* the first block with any messages.

One thing to note is that this is using the same block pubsub topic as the 0.3 network, so nodes will be receiving a bunch of invalid blocks, possibly even trying to sync the wrong chain. We should change this topic for the same reasons we changed it for 0.3 - we're not learning anything from this unintended "spam" until we implement secure bootstrapping.

**To Reproduce**
Join a new node to 0.4.0
```
./go-filecoin init --devnet-staging --genesisfile=https://genesis.staging.kittyhawk.wtf/genesis.car
./go-filecoin daemon
```

Others have reported their chain sync stopping at the same height.

**Expected behavior**
Chain sync continues!

### PR DESCRIPTION
**Pull request by anorth**
With these changes, I have synced a node to the 0.4.0 staging devnet.

Fixes #3220

### CODE REVIEW

**Comment by hannahhoward** [comment]
@anorth this works but I believe the fix to the selector is more efficient than recursion depth+1. Recursion depth +1 will fetch an extra set of block headers.

**Comment by anorth** [comment]
I agree

**Comment by anorth** [comment]
Yes, I'm doing just that right now.

File: net/graphsync_fetcher.go [hunk 1]
```diff
@@ -101,26 +102,33 @@ func (gsf *GraphSyncFetcher) FetchTipSets(ctx context.Context, tsKey types.TipSe
...
-		err := gsf.fetchBlocks(ctx, cids, rpf.CurrentPeer())
-		if err == nil {
-			break
-		}
-		// something went wrong in a graphsync request, but we want to keep trying other peers, so
-		// just log error
-		logGraphsyncFetcher.Infof("Error occurred during Graphsync request: %s", err)
-		cids, err = gsf.missingCids(cids)
+		peer := rpf.CurrentPeer()
+		logGraphsyncFetcher.Infof("fetching initial tipset %s from peer %s", key, peer)
```
[the remark this answers is not in the document]
Comment (anorth) [reply net/graphsync_fetcher.go]: This was intentional (with the expectation that graphsync internally would avoid actually fetching the already-stored blocks). However I've since reverted to the original logic (with better verification) as, coupled with the parallel requests, the change too hard to work with the existing unit tests.

File: chain/get_ancestors_test.go [hunk 2]
```diff
@@ -68,7 +68,7 @@ func TestCollectTipSetsOfHeightAtLeastStartingEpochIsNull(t *testing.T) {
 	head = builder.AppendManyOn(30, head)
 
 	// Now add 10 null blocks and 1 tipset.
-	head = builder.BuildOn(head, func(b *chain.BlockBuilder) {
+	head = builder.BuildOneOn(head, func(b *chain.BlockBuilder) {
```
Comment (anorth) [inline chain/get_ancestors_test.go]: Sorry about the noise here, I renamed this to make room for `BuildOn` to build multiple peer blocks (like `AppendOn`).

File: net/graphsync_fetcher.go [hunk 3]
```diff
@@ -210,14 +222,17 @@ func (gsf *GraphSyncFetcher) fetchBlocksRecursively(ctx context.Context, baseCid
...
-		efsb.Insert("messages", gsf.ssb.Matcher())
-		efsb.Insert("messageReceipts", gsf.ssb.Matcher())
 		efsb.Insert("parents", gsf.ssb.ExploreUnion(
-			gsf.ssb.ExploreAll(gsf.ssb.Matcher()),
+			gsf.ssb.ExploreAll(
+				gsf.ssb.ExploreFields(func(efsb selectorbuilder.ExploreFieldsSpecBuilder) {
+					efsb.Insert("messages", gsf.ssb.Matcher())
+					efsb.Insert("messageReceipts", gsf.ssb.Matcher())
+				}),
+			),
```
Comment (anorth) [inline net/graphsync_fetcher.go]: This is the real fix (thanks to @hannahhoward). Most of the rest of the change in this file is additionally verifying that the blocks for the message and receipt lists are actually stored (along with the block headers which were already verified).

File: net/graphsync_fetcher.go [hunk 4]
```diff
@@ -229,46 +244,65 @@ func (gsf *GraphSyncFetcher) fetchBlocksRecursively(ctx context.Context, baseCid
...
+			// TODO: validate the structures, don't just check for their presence #3232
+			ok, err := gsf.store.Has(link)
+			if err != nil {
+				return types.UndefTipSet, nil, err
+			}
+			if !ok {
+				incomplete = append(incomplete, blk.Cid())
+			}
+		}
+	}
```
Comment (anorth) [inline net/graphsync_fetcher.go]: That verification could be considered redundant if we trusted graphsync to be correct and that we were using it properly - but in this case having it in the first place would have immediately exposed that we *weren't* using it properly. Since we should also validate the syntax of those other structures before accepting them, I don't think checking for them is wasteful work in the long run.

File: net/graphsync_fetcher_test.go [hunk 5]
```diff
@@ -43,58 +43,78 @@ func TestGraphsyncFetcher(t *testing.T) {
...
+			nodes[3*i] = b.ToNode()
+			m, err := builder.LoadMessages(ctx, b.Messages)
+			require.NoError(t, err)
+			nodes[3*i+1] = types.MessageCollection(m).ToNode()
+			r, err := builder.LoadReceipts(ctx, b.MessageReceipts)
+			require.NoError(t, err)
+			nodes[3*i+2] = types.ReceiptCollection(r).ToNode()
+		}
+		return nodes
+	}
```
Comment (anorth) [inline net/graphsync_fetcher_test.go]: Most of the change in this file is to return the correct data (i.e. including message/receipt lists) to the fetcher, which now checks for it.

**Comment by taylorshuang** [comment]
anorth，If I want to fix this bug, how can I compile it into v0.4.0?
