### PR TITLE
Fix Flaky TestStorageDealsAfterRestart

### LINKED ISSUE #1873: [bug] Flaky test TestPaymentChannelReclaimSuccess and TestStorageDealsAfterRestart
**Describe the bug**
Flaky test: TestPaymentChannelReclaimSuccess

**To Reproduce**
Run CI

**Expected behavior**
Test should never fail.

**Screenshots**
https://circleci.com/gh/filecoin-project/go-filecoin/10794?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Desktop (please complete the following information):**
 Travis CI

**Additional context**
Haven't seen this before and couldn't find another issue reporting

### PR DESCRIPTION
**Pull request by rkowalick**
Resolves #1873 

## Problem

Test would fail with "ask not found" when the storage client would attempt to propose a storage deal

## Solution

Wait for the storage client node to see the AddAsk message generated by the storage miner node before making the storage deal proposal.

### CODE REVIEW

File: build/main.go [hunk 1]
```diff
@@ -335,7 +335,7 @@ func install() {
 func test(args ...string) {
 	log.Println("Testing...")
 
-	runCmd(cmd(fmt.Sprintf("go test -timeout 30m -parallel 8 ./... %s", strings.Join(args, " "))))
+	runCmd(cmd(fmt.Sprintf("go test -timeout 30m -run TestStorageDealsAfterRestart -count=100 -parallel 8 ./... %s", strings.Join(args, " "))))
```
Comment (rkowalick) [inline build/main.go]: *MUST BE REMOVED BEFORE MERGE*

File: commands/client_daemon_test.go [hunk 2]
```diff
@@ -46,7 +46,8 @@ func TestStorageDealsAfterRestart(t *testing.T) {
 
 	minerDaemon.ConnectSuccess(clientDaemon)
 
-	minerDaemon.MinerSetPrice(fixtures.TestMiners[0], fixtures.TestAddresses[0], "20", "10")
+	addAskCid := minerDaemon.MinerSetPrice(fixtures.TestMiners[0], fixtures.TestAddresses[0], "20", "10")
```
Comment (shannonwells) [inline commands/client_daemon_test.go]: AHA.

File: testhelpers/commands.go [hunk 3]
```diff
@@ -487,9 +487,27 @@ func (td *TestDaemon) CreateMinerAddr(peer *TestDaemon, fromAddr string) address
 	return minerAddr
 }
 
-// MinerSetPrice creates an ask for a CURRENTLY MINING test daemon and waits for it to appears on chain
-func (td *TestDaemon) MinerSetPrice(minerAddr string, fromAddr string, price string, expiry string) {
-	td.RunSuccess("miner", "set-price", "--from", fromAddr, "--miner", minerAddr, "--gas-price", "0", "--gas-limit", "300", price, expiry)
+// MinerSetPrice creates an ask for a CURRENTLY MINING test daemon and waits for it to appears on chain. It returns the
+// cid of the AddAsk message so other daemons can `message wait` for it.
+func (td *TestDaemon) MinerSetPrice(minerAddr string, fromAddr string, price string, expiry string) cid.Cid {
```
Comment (shannonwells) [inline testhelpers/commands.go]: if you're adding a require in here, this should be renamed to RequireMinerSetPrice, following the convention that we (mostly) have already.
