### PR TITLE
Bugs/action client ignores allow duplicates

### LINKED ISSUE #3150: [bug] FAST action_client/ClientProposeStorageDeal ignores allowDuplicates flag
**Describe the bug**
As the subject line says

**To Reproduce**
I have rewritten the test for duplicate deals to use FAST so it will show red/green test behavior: putting back the old behavior the test fails, and with the new code that uses the allowDuplicates flag it passes.  Logging the error output shows that the test fails because duplicate deals aren't allowed because the CLI was not passed `--allow-duplicates`.

### PR DESCRIPTION
**Pull request by shannonwells**
# Problem
Closes #3150 , FAST `ClientProposeDeal` was ignoring the allowDuplicates flag.  Discovered while writing an integration test for another story.

# Solution
- Pass --allow-duplicates as a parameter according to the flag.  
- Update `TestDuplicateDeals` from old-style daemon test to FAST, so it now uses this function `ClientProposeDeal`.

with @ingar

### CODE REVIEW

File: commands/client_daemon_test.go [hunk 1]
```diff
@@ -78,39 +80,61 @@ func TestStorageDealsAfterRestart(t *testing.T) {
...
-	defer miner.ShutdownSuccess()
-
-	client := th.NewDaemon(t, th.KeyFile(fixtures.KeyFilePaths()[2]), th.DefaultAddress(fixtures.TestAddresses[2])).Start()
-	defer client.ShutdownSuccess()
+	// Give the deal time to complete
+	ctx, env := fastesting.NewTestEnvironment(context.Background(), t, fast.FilecoinOpts{
+		InitOpts:   []fast.ProcessInitOption{fast.POAutoSealIntervalSeconds(1)},
+		DaemonOpts: []fast.ProcessDaemonOption{fast.POBlockTime(50 * time.Millisecond)},
+	})
+	defer func() {
```
Comment (frrist) [inline commands/client_daemon_test.go]: I think we can just do:
`defer 		require.NoError(t, env.Teardown(ctx))`
Same with the below.

File: tools/fast/action_client.go [hunk 2]
```diff
@@ -44,7 +44,16 @@ func (f *Filecoin) ClientProposeStorageDeal(ctx context.Context, data cid.Cid,
 	sAsk := fmt.Sprintf("%d", ask)
 	sDuration := fmt.Sprintf("%d", duration)
 
-	if err := f.RunCmdJSONWithStdin(ctx, nil, &out, "go-filecoin", "client", "propose-storage-deal", sMiner, sData, sAsk, sDuration); err != nil {
+	// RunCmd does not allow empty arguments (e.g. in the cast that allowDuplicates is false, use an
```
Comment (frrist) [inline tools/fast/action_client.go]: I think you can just do `--allow-duplicates=true` and  `--allow-duplicates=false`

Comment (frrist) [reply tools/fast/action_client.go]: also cast -> case if we keep this comment

File: tools/fast/process.go [hunk 3]
```diff
@@ -199,6 +200,16 @@ func (f *Filecoin) LastCmdStdErr() io.ReadCloser {
 	return f.lastCmdOutput.Stderr()
 }
 
+// LastCmdStdErrStr is a shortcut to just get the output as string
+func (f *Filecoin) LastCmdStdErrStr() string {
```
Comment (frrist) [inline tools/fast/process.go]: Blocking: This is nice to have, but let's return an error here for the case that reading fails.

File: commands/client_daemon_test.go [hunk 4]
```diff
@@ -78,39 +79,61 @@ func TestStorageDealsAfterRestart(t *testing.T) {
 
 func TestDuplicateDeals(t *testing.T) {
 	tf.IntegrationTest(t)
+	logging.SetDebugLogging()
 
-	miner := th.NewDaemon(t,
```
Comment (frrist) [inline commands/client_daemon_test.go]: :champagne: :fireworks: :tada: :medal_sports: :1st_place_medal: :100:

File: tools/fast/action_client.go (hunk 2 above)
Comment (travisperson) [reply tools/fast/action_client.go]: We should probably move this to the other pattern by using a variadic argument for flags.

@shannonwells good example: https://github.com/filecoin-project/go-filecoin/blob/master/tools/fast/action_miner.go#L18-L36

You can then add a function in https://github.com/filecoin-project/go-filecoin/blob/master/tools/fast/process_action_options.go

File: commands/client_daemon_test.go [hunk 5]
```diff
@@ -78,39 +79,61 @@ func TestStorageDealsAfterRestart(t *testing.T) {
 
 func TestDuplicateDeals(t *testing.T) {
 	tf.IntegrationTest(t)
+	logging.SetDebugLogging()
```
[the remark this answers is not in the document]
Comment (shannonwells) [reply commands/client_daemon_test.go]: yep thanks

File: tools/fast/process.go (hunk 3 above)
Comment (shannonwells) [reply tools/fast/process.go]: meh, I was hoping to leave it since returning the error string will cause a test failure, and the dev will see immediately why, however it does break patterns...
