### PR TITLE
Fix for setting block time in FilecoinOpts

### LINKED ISSUE #2900: [bug] Providing DaemonOpts to fastesting.NewTestEnvironment somehow causing repo/api not found
## Describe the bug
When creating a FAST test, I attempted to pass a DaemonOpt for increasing the block time to `fastesting.NewTestEnvironment`.  This consistently will cause the following error:

```Could not get PeerID, non-zero exit code```

but when you turn on logging with `log.SetDebugLogging()`, you'll see why:
```
13:16:45.796 WARNI  util: open  /var/folders/j0/foo...bar/T/TestReproduceFASTFailure613116831/0/repo/api: no such file or directory util.go:27
```
One of these messages occurs with the default options, i.e. passing in `fast.FilecoinOpts{}`, but adding an option results in this file never being found at all, so it looks like the api is for some reason never created, or maybe it's looking in the wrong directory or ?

## To Reproduce
Use the following code to reproduce the behavior. By commenting out the `DaemonOpts` line (and removing the "time" import), the test will pass, leaving it will fail.
```
func TestReproduceFASTFailure(t *testing.T){
	tf.IntegrationTest(t)
	log.SetDebugLogging()

	fastOpts := fast.FilecoinOpts{
		DaemonOpts: []fast.ProcessDaemonOption{fast.POBlockTime(time.Second)},
	}

	ctx, env := fastesting.NewTestEnvironment(context.Background(), t, fastOpts)

	clientNode := env.GenesisMiner
	require.NoError(t, clientNode.MiningStart(ctx))
}
```

## Expected
Opts passed to NewTestEnvironment should be successfully merged with default settings, and also should not prevent the test from running.

### Reproduces: 100%

### PR DESCRIPTION
**Pull request by shannonwells**
Closes #2900
This is a workaround for the bug found in the above issue. 
I considered a few approaches before settling on this and I'm not thrilled with it, but it seems to be the best of not great solutions.

Bonus: this ought to reduce CI time since FAST is back down to a 1ms default block time.

# Considered alternatives
*  Fixing the source of the bug.  Drilling down to figure out why having two --block-time options sent to RunCmd would cause a failure to find the api file was taking a lot of time.
*  DefaultFilecoinOpts struct, or a CreateDefaultFilecoinOpts function that returns all the defaults, both InitOpts and DaemonOpts. The problem with this is setting up the genesis, which depends on the genesis environment you want to run. These need to be declared together because the URI has to come from that environment instance.
* The struct or function creating the defaults has only DaemonOpts, not InitOpts.  Not ideal because it's not really all the defaults.  Also this and the above would require changing 9 other files and even more tests.

# Chosen solution
* I landed on splitting up the treatment of InitOpts and DaemonOpts in NewTestEnvironment. 
    - InitOpts must append the genesis URL regardless, so this line stays the same.
    - Check DaemonOpts, and if it is empty, we'll set a 1ms block time.  There is no easy and accurate way to match opt functions to determine if there is already a block time option set.  Doing advanced checking with reflections seems like overkill. I did not want to go deeper into FAST code to reject duplicate option strings.  Commandkit already rejects duplicate options on the command line.
- I added a comment that if you do pass in non-empty DaemonOpts you should set your own block time.

### CODE REVIEW

**Comment by anorth** [comment]
@shannonwells please assign reviewers if you want to land this

**Comment by shannonwells** [comment]
> @shannonwells please assign reviewers if you want to land this

I need to get it passing tests and then got busy & forgot about it... I'll mark it as WIP until I can get back to it

File: tools/fast/fastesting/basic_test.go [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+
+func TestSetFilecoinOpts(t *testing.T) {
+	tf.IntegrationTest(t)
+	log.SetDebugLogging()
+
+	fastOpts := fast.FilecoinOpts{
+		DaemonOpts: []fast.ProcessDaemonOption{fast.POBlockTime(10 * time.Millisecond)},
+	}
+
+	ctx, env := fastesting.NewTestEnvironment(context.Background(), t, fastOpts)
```
Comment (frrist) [inline tools/fast/fastesting/basic_test.go]: We need a call like the below to avoid leaking processes since this method starts one:
```go
	// Teardown after test ends
	defer func() {
		err := env.Teardown(ctx)
		require.NoError(t, err)
	}()
```

File: tools/fast/fastesting/basic.go [hunk 2]
```diff
@@ -59,9 +62,12 @@ func NewTestEnvironment(ctx context.Context, t *testing.T, fastenvOpts fast.File
 	genesisMiner, err := env.GenesisMiner()
 	require.NoError(t, err)
 
-	fastenvOpts = fast.FilecoinOpts{
-		InitOpts:   append([]fast.ProcessInitOption{fast.POGenesisFile(genesisURI)}, fastenvOpts.InitOpts...),
-		DaemonOpts: append([]fast.ProcessDaemonOption{fast.POBlockTime(100 * time.Millisecond)}, fastenvOpts.DaemonOpts...),
+	fastenvOpts.InitOpts = append([]fast.ProcessInitOption{fast.POGenesisFile(genesisURI)}, fastenvOpts.InitOpts...)
+
+	// The old method appended a default blocktime and this caused a bug when callers set blocktime
+	// as well. See Issue
```
Comment (frrist) [inline tools/fast/fastesting/basic.go]: Se should link to the issue or remove this comment

File: tools/fast/fastesting/basic.go [hunk 3]
```diff
@@ -59,9 +62,12 @@ func NewTestEnvironment(ctx context.Context, t *testing.T, fastenvOpts fast.File
...
+	if len(fastenvOpts.DaemonOpts) == 0 {
```
Comment (frrist) [inline tools/fast/fastesting/basic.go]: Should we instead explicitly check if the `POBlockTime` opt was passed here? There could be daemon opts passed that are unrelated to block time.

Comment (shannonwells) [reply tools/fast/fastesting/basic.go]: do you know how to do that? I couldn't figure out how

Comment (travisperson) [reply tools/fast/fastesting/basic.go]: I don't think there is a super clean way to actually check if the blocktime was passed. I guess the best thing to do would be to iterator over all `DaemonOpts` invoking them and doing a check for `--block-time`.

This might be the best way to move forward at the moment.

```
isBlockTimeSet := false
for _, fn := range fastenvOpts.DaemonOpts {
	s := fn()
	if len(s) > 0 && s[0] == "--block-time" {
		isBlockTimeSet = true
		break
	}
}
```

Currently the requirement to change the blocktime stems from an issue of having to use `MiningStart` to get around an issue where the storage protocol and sector builder is tied to mining. I have an issue to track this in #2968.

So I'm not sure how common it's going to be to actually want to change the blocktime after we get a fix in. The issue we face is that the actual default of 30s is not what we want to default to in these tests most of the time. So I think regardless we are going to want to be able to detect block-time being passed, and add the daemon opt if it's not provided.

Comment (shannonwells) [reply tools/fast/fastesting/basic.go]: Ok so should this change be isolated to detecting if a block time was passed in and then adding one if it's not?

File: tools/fast/fastesting/basic_test.go (hunk 1 above)
Comment (shannonwells) [reply tools/fast/fastesting/basic_test.go]: good catch

File: tools/fast/fastesting/basic.go (hunk 3 above)
Comment (travisperson) [reply tools/fast/fastesting/basic.go]: Ya, I think everything else in this PR looks good.
