### PR TITLE
Bugs/flaky testtipsetweightdeep #1828

### LINKED ISSUE #1828: [bug] Flaky TestTipSetWeightDeep "not a winning ticket"
**Describe the bug**
@anorth reported flaky behavior in `TestTipSetWeightDeep` on CI:

**To Reproduce**
Cannot reproduce locally.

**Expected behavior**
This test should never fail

**Screenshots**
```
--- FAIL: TestTipSetWeightDeep (18.15s)
    require.go:794: 
            Error Trace:    default_syncer_test.go:911
            Error:          Received unexpected error:
                            not a winning ticket
                            github.com/filecoin-project/go-filecoin/consensus.(*Expected).validateMining
                                /go/src/github.com/filecoin-project/go-filecoin/consensus/expected.go:298
```
**Desktop (please complete the following information):**
CI

**Additional context**
Should be straightforward to identify source of entropy as this is not a daemon test and doesn't do any networking stuff.

### PR DESCRIPTION
**Pull request by shannonwells**
1. Fixes #1828 , flaky `TestTipSetWeightDeep` in default_syncer_test.go
1. puts chain tests into their own package so they can be run individually simply with 
        `go test <filename>`
    or even specify a single test case like a civilized person such as
        `go test <filename> -run <simple regex>"` 
    This is another argument in favor of not making tests part of the package they are testing.
1. Also adds another build command, "fbuild" which forces a build of everything (including deps), which I added while debugging unrelated environment issues.

### CODE REVIEW

**Comment by phritz** [comment]
can you tell me about why we need force build? not saying we dont, just asking what problem it solves.

**Comment by shannonwells** [comment]
> can you tell me about why we need force build? not saying we dont, just asking what problem it solves.

I used it to rule out certain issues when debugging this test and also some environment issues. If no one else thinks it'll be useful I'll take it out.

File: chain/default_syncer_test.go [hunk 1]
```diff
@@ -790,35 +791,35 @@ func TestTipSetWeightDeep(t *testing.T) {
 	var calcGenBlk types.Block
 	require.NoError(cst.Get(ctx, info.GenesisCid, &calcGenBlk))
 
-	// chain.Store
-	chain := NewDefaultStore(r.ChainDatastore(), cst, calcGenBlk.Cid())
+	// chainStore.Store
```
Comment (phritz) [inline chain/default_syncer_test.go]: global search and replace gone amok here and in comment on 797

File: chain/default_syncer_test.go [hunk 2]
```diff
@@ -893,9 +893,12 @@ func TestTipSetWeightDeep(t *testing.T) {
 	f2b2 := RequireMkFakeChildCore(require,
 		FakeChildParams{Parent: testhelpers.RequireNewTipSet(require, f2b1), GenesisCid: calcGenBlk.Cid(), StateRoot: bootstrapStateRoot, MinerAddr: info.Miners[3].Address},
 		wFun)
+	// This should fix https://github.com/filecoin-project/go-filecoin/issues/1828
```
Comment (shannonwells) [inline chain/default_syncer_test.go]: @phritz This last block did not have a Proof and winning Ticket.  It's surprising it didn't fail more often.

File: chain/default_syncer_test.go [hunk 3]
```diff
@@ -790,35 +791,35 @@ func TestTipSetWeightDeep(t *testing.T) {
...
-	syncer := NewDefaultSyncer(cst, cst, con, chain)
-	baseTS := chain.Head() // this is the last block of the bootstrapping chain creating miners
+	syncer := chain.NewDefaultSyncer(cst, cst, con, chainStore)
+	baseTS := chainStore.Head() // this is the last block of the bootstrapping chainStore creating miners
 	require.Equal(1, len(baseTS))
 	bootstrapStateRoot := baseTS.ToSlice()[0].StateRoot
 	pSt, err := state.LoadStateTree(ctx, cst, baseTS.ToSlice()[0].StateRoot, builtin.Actors)
 	require.NoError(err)
-	/* Test chain diagram and weight calcs */
+	/* Test chainStore diagram and weight calcs */
```
Comment (phritz) [inline chain/default_syncer_test.go]: test chain

File: chain/default_syncer_test.go [hunk 4]
```diff
@@ -790,35 +791,35 @@ func TestTipSetWeightDeep(t *testing.T) {
...
+	requireTsAdded(require, chainStore, calcGenTS)
 
-	// Now sync the chain with consensus using a MarketView.
+	// Now sync the chainStore with consensus using a MarketView.
 	verifier = proofs.NewFakeVerifier(true, nil)
 	con = consensus.NewExpected(cst, bs, testhelpers.NewTestProcessor(), &consensus.MarketView{}, calcGenBlk.Cid(), verifier)
-	syncer := NewDefaultSyncer(cst, cst, con, chain)
-	baseTS := chain.Head() // this is the last block of the bootstrapping chain creating miners
+	syncer := chain.NewDefaultSyncer(cst, cst, con, chainStore)
+	baseTS := chainStore.Head() // this is the last block of the bootstrapping chainStore creating miners
```
Comment (phritz) [inline chain/default_syncer_test.go]: chain

File: chain/default_syncer_test.go [hunk 5]
```diff
@@ -790,35 +791,35 @@ func TestTipSetWeightDeep(t *testing.T) {
...
 	calcGenTS := testhelpers.RequireNewTipSet(require, &calcGenBlk)
-	genTsas := &TipSetAndState{
+	genTsas := &chain.TipSetAndState{
 		TipSet:          calcGenTS,
 		TipSetStateRoot: calcGenBlk.StateRoot,
 	}
-	RequirePutTsas(ctx, require, chain, genTsas)
-	err = chain.SetHead(ctx, calcGenTS) // Initialize chain store with correct genesis
+	chain.RequirePutTsas(ctx, require, chainStore, genTsas)
+	err = chainStore.SetHead(ctx, calcGenTS) // Initialize chainStore store with correct genesis
```
Comment (phritz) [inline chain/default_syncer_test.go]: chain store

**Comment by shannonwells** [comment]
> can you tell me about why we need force build? not saying we dont, just asking what problem it solves.

Weird, I thought I had put something about that in this PR. Anyway, see my comment in default_syncer_test.go.  We were missing one last place where it needed a Proof and winning Ticket.

File: chain/default_syncer_test.go [hunk 6]
```diff
@@ -746,8 +747,8 @@ func TestHeaviestIsWidenedAncestor(t *testing.T) {
 
 	// Assert that widened chain is the new head
 	wideTs := testhelpers.RequireNewTipSet(require, link2blk1, link2blk2, link2blk3, forklink2blk1, forklink2blk2, forklink2blk3, forklink2blk4)
-	assertTsAdded(assert, chain, wideTs)
-	assertHead(assert, chain, wideTs)
+	assertTsAdded(assert, chainStore, wideTs)
+	assertHead(assert, chainStore, wideTs)
 }
 
 /* Tests with Unmocked state */
```
Comment (phritz) [inline chain/default_syncer_test.go]: is the comment below still accurate? seems like weird to leave it in a mysterious state

File: chain/default_syncer_test.go [hunk 7]
```diff
@@ -858,48 +859,58 @@ func TestTipSetWeightDeep(t *testing.T) {
...
 
 	// fork 2 has heavier weight because of addr3's power even though there
 	// are fewer blocks in the tipset than fork 1.
-	f2b2 := RequireMkFakeChildCore(require,
-		FakeChildParams{Parent: testhelpers.RequireNewTipSet(require, f2b1), GenesisCid: calcGenBlk.Cid(), StateRoot: bootstrapStateRoot, MinerAddr: info.Miners[3].Address},
+	f2b2 := chain.RequireMkFakeChildCore(require,
+		chain.FakeChildParams{Parent: testhelpers.RequireNewTipSet(require, f2b1), GenesisCid: calcGenBlk.Cid(), StateRoot: bootstrapStateRoot, MinerAddr: info.Miners[3].Address},
 		wFun)
+	// This should fix https://github.com/filecoin-project/go-filecoin/issues/1828
+	f2b2.Proof, f2b2.Ticket, err = chain.MakeProofAndWinningTicket(info.Miners[3].Address, info.Miners[3].Power, 1000)
```
Comment (phritz) [inline chain/default_syncer_test.go]: can you splain what the issue was and the fix? like, how did this pass and what caused the nondeterminism?

Comment (shannonwells) [reply chain/default_syncer_test.go]: My best guess is it was because that block's miner power was 980 compared to 1000 total Power, so most of the time it was a winning ticket because of the extremely large "stake".

File: chain/default_syncer_test.go (hunk 6 above)
Comment (shannonwells) [reply chain/default_syncer_test.go]: I don't know; it's weird to me too and I haven't gotten around to asking about it/looking into it.
